version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - python --version
      - pip --version
      - pip install pipx
      - python -m pipx install poetry
      - python -m pipx ensurepath
      - source ~/.bashrc
      - make build
  build:
    commands:
      - poetry build
