version: 0.2

env:
  variables:
    branch: ""

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - python --version
      - pip --version
      - pip install pipx
      - python -m pipx install poetry
      - python -m pipx ensurepath
      - source ~/.bashrc
  build:
    commands:
      - git checkout ${branch}
      - make build

artifacts:
  files:
    - "**/*"
  base-directory: package
  name: hcw-api-app
