version: 0.2

env:
  variables:
    environment_name: "ianr-test"
    account_name: "dev"

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
      - cd infrastructure
      - pwd
      - terraform init
      - terraform workspace list
      - # TODO: Check workspace exists first (-or-create)
      - terraform workspace select ${environment_name}
      - terraform plan -var-file="environments/${account_name}.tfvars" -out tf.plan
      - terraform apply tf.plan
  build:
    commands:
      make

