version: 0.2

env:
  variables:
    environment_name: "ianr-test"
    account_name: "dev"
    app_s3_filename: "c0130d95-d26d-4f26-9486-e2dd745e68a0/hcw-api-build.zip"

phases:
  install:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform --version
  build:
    commands:
      - cd infrastructure
      - terraform init
      - terraform workspace select -or-create ${environment_name}
      - terraform plan -var-file="environments/${account_name}.tfvars" -var "app_s3_filename=${app_s3_filename}" -out tf.plan
      - terraform apply tf.plan

