openapi: 3.0.3
info:
  version: v0.1
  title: Healthcare Worker API
paths:
  /Worker:
    get:
      summary: Get healthcare worker details
      parameters:
        - in: query
          name: identifier
          description: SDS user ID which uniquely identifies a person.
          required: true
          example: 123456789012
          schema:
            type: string
          explode: true
        - in: header
          name: X-Correlation-Id
          description: UUID for request tracking
          schema:
            type: string
            format: uuid
          required: false
          example: 6d3d3674-7ce5-11ec-90d6-0242ac120003
        - in: header
          name: apikey
          description: API key to authenticate with. Use any value for Sandbox environment.
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  person:
                    $ref: '#/components/schemas/Worker'
        '400':
          description: Missing or invalid query parameter(s).
        '404':
          description: Invalid endpoint path
        '405':
          description: Unsupported HTTP method. For this endpoint only GET is available
        '406':
          description: Unsupported media type
        '500':
          description: Unhandled internal server error
        '502':
          description: Upstream LDAP returned an unsupported responses
        '504':
          description: Upstream LDAP server request has timed out
      'x-amazon-apigateway-integration':
        credentials: '${lambda_invocation_arn}'
        responses:
          default:
            statusCode: 200
            responseParameters:
            responseTemplates:
        uri: '${lambda_uri}'
        passthroughBehaviour: 'when_no_match'
        httpMethod: POST
        type: 'aws'
components:
  schemas:
    Worker:
      type: object
      properties:
        id:
          type: string
          description: Auto generated unique Spine ID for the person.
          example: 123456789012
        forename:
          type: string
          description: The forename or given name of a person.
          example: Jane
        surname:
          type: string
          description: That part of a person's name which is used to describe family, clan, tribal group, or marital association.
          example: Smith
        initials:
          type: string
          description: All middle initials, excludes first name initial.
          example: A
        title:
          type: string
          description: Standard form of address used to precede a person's name
          example: Ms
        orgPersons:
          type: array
          description: Information relating a person to a specific organisation.
          items:
            type: object
            properties:
              id:
                type: string
                description: Auto generated unique Spine ID for the organisational person.
                example: 345678901234
              dateOpened:
                type: string
                description: Date organisational person was opened/re-opened. (yyyymmdd)
                example: 20210131
              dateClosed:
                type: string
                description: Date organisational person was closed (yyyymmdd).
                example: 20240927
              orgName:
                type: string
                description: Official name for the associated organisation, taken from ODS.
                example: THE CROOKES PRACTICE
              orgId:
                type: string
                description: Official code for the associated organisation, taken from ODS.
                example: G7125085
              roleProfiles:
                type: array
                description: The details of a user’s specific roles within a specific organisation.
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Auto generated unique Spine ID for the role profile.
                      example: 567890123456
        active:
          type: boolean
          description: A value of true indicates the person's care identity is active. A value of false indicates inactive.
          example: true
