[tool.poetry]
name = "status-reporting"
version = "0.1.0"
description = ""
authors = ["Ian Robinson <ian.robinson27@nhs.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
