name: "Build stage"

on:
  workflow_call:
    inputs:
      build_datetime:
        description: "Build datetime, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_timestamp:
        description: "Build timestamp, set by the CI/CD pipeline workflow"
        required: true
        type: string
      build_epoch:
        description: "Build epoch, set by the CI/CD pipeline workflow"
        required: true
        type: string
      nodejs_version:
        description: "Node.js version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      python_version:
        description: "Python version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      terraform_version:
        description: "Terraform version, set by the CI/CD pipeline workflow"
        required: true
        type: string
      version:
        description: "Version of the software, set by the CI/CD pipeline workflow"
        required: true
        type: string

jobs:
  hcw-api-app:
    name: "HCW API App"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Build HCW Api Lambda App"
        run: |
          ./scripts/build-app.sh
      - name: "Check app build output"
        run: |
          if [ ! -f hcw-api.zip ]; then
            echo "Did not find expected zip as result of app build"
            exit 1
          fi
      - name: "Upload app build to S3"
        run: |
          ./scripts/deploy-app.sh dev
        env:
          AWS_ACCESS_KEY_ID: ${{  }}
          AWS_SECRET_ACCESS_KEY: ${{ }}
          AWS_DEFAULT_REGION: "eu-west-2"
